#!/bin/python3

# Problem Statement : Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#       1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

# Author : Amol Kahat
# Email : amolkahat@gmail.com

lim = 4000000
i = 0
j = 1
even_fib_sum = 0
while j < lim:
    no = i +j
    if no % 2 == 0 and no < lim:
        even_fib_sum += no
    i, j = j, no

print("Even no addition : " + str(even_fib_sum))
